# Generated by Django 5.1.6 on 2025-02-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='chat_id',
            field=models.CharField(blank=True, help_text='Это поле заполнится автоматически после старта бота', max_length=100, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='username',
            field=models.CharField(help_text='Введите username без символа @', max_length=255, unique=True, verbose_name='Telegram username (без @)'),
        ),
    ]
